### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by suitougreentea** [bemusic/bmson-spec#1]
- [x] Prettify
  - Includes removal of line length limitation
- [x] Recover code block
- [x] Fix in-page links
- [x] Resolve in-doc TODO
- [x] Rename image

**Comment by suitougreentea** [comment]
- [x] error in time signature
